#pragma once

#define DEFAULT_WINDOW_WIDTH			800
#define DEFAULT_WINDOW_HEIGHT			600

#define DEFAULT_SHADOW_WIDTH			1024
#define DEFAULT_SHADOW_HEIGHT			1024

#define IMGUI_TEXTURE_UNIT				0x84C0

#define GBUFFER_COLOR_BUFFER0_UNIT		0x84C1
#define GBUFFER_COLOR_BUFFER1_UNIT		0x84C2
#define GBUFFER_COLOR_BUFFER2_UNIT		0x84C3
#define GBUFFER_COLOR_BUFFER3_UNIT		0x84C4
#define GBUFFER_DEPTH_BUFFER_UNIT		0x84C5

#define LIGHT_ACCUMULATION_BUFFER_UNIT	0x84C6

#define SHADOW_MAP_TEXTURE_UNIT			0x84C7
#define REFLECTION_MAP_TEXTURE_UNIT		0x84C8
#define DIFFUSE_MAP_TEXTURE_UNIT		0x84C9
#define NORMAL_MAP_TEXTURE_UNIT			0x84CA
#define SPECULAR_MAP_TEXTURE_UNIT		0x84CB
